Resources:
  ssminstancerole0E7D791C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - ec2.
                    - Ref: AWS::URLSuffix
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonSSMManagedInstanceCore
    Metadata:
      aws:cdk:path: FisExampleStack/ssm-instance-role/Resource
  instance0InstanceSecurityGroup56F2543E:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: FisExampleStack/instance-0/InstanceSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId:
        Ref: VPCParameterValue
      Tags:
        - Key: FIS-Target
          Value: "true"
        - Key: Name
          Value: FisExampleStack/instance-0
  instance0InstanceProfile493621FA:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: ssminstancerole0E7D791C
    Metadata:
      aws:cdk:path: FisExampleStack/instance-0/InstanceProfile
  instance0B661231D:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      IamInstanceProfile:
        Ref: instance0InstanceProfile493621FA
      ImageId:
        Ref: SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: t3a.nano
      SecurityGroupIds:
        - Fn::GetAtt:
            - instance0InstanceSecurityGroup56F2543E
            - GroupId
      Tags:
        - Key: FIS-Target
          Value: "true"
        - Key: Name
          Value: FisExampleStack/instance-0
      UserData:
        Fn::Base64: "#!/bin/bash"
    DependsOn:
      - ssminstancerole0E7D791C
  cwalarm8A77F56F:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      AlarmName: NetworkInAbnormal
      DatapointsToAlarm: 1
      Dimensions:
        - Name: InstanceId
          Value:
            Ref: instance0B661231D
      MetricName: NetworkIn
      Namespace: AWS/EC2
      Period: 60
      Statistic: Average
      Threshold: 10
      TreatMissingData: missing
    Metadata:
      aws:cdk:path: FisExampleStack/cw-alarm/Resource
  fisrole33E76559:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: fis.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEC2FullAccess
    Metadata:
      aws:cdk:path: FisExampleStack/fis-role/Resource
  fisroleDefaultPolicy53088256:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ssm:SendCommand
              - ssm:ListCommands
              - ssm:CancelCommands
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: fisroleDefaultPolicy53088256
      Roles:
        - Ref: fisrole33E76559
    Metadata:
      aws:cdk:path: FisExampleStack/fis-role/DefaultPolicy/Resource
  fistemplatedemostopinstance:
    Type: AWS::FIS::ExperimentTemplate
    Properties:
      Description: Demo for Stopping and Starting a single instance via instance id
      RoleArn:
        Fn::GetAtt:
          - fisrole33E76559
          - Arn
      StopConditions:
        - Source: aws:cloudwatch:alarm
          Value:
            Fn::GetAtt:
              - cwalarm8A77F56F
              - Arn
      Tags:
        Name: StopStartInstanceById
      Targets:
        instanceTargets:
          ResourceType: aws:ec2:instance
          SelectionMode: ALL
          ResourceArns:
            - Fn::Join:
                - ""
                - - "arn:aws:ec2:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :instance/
                  - Ref: instance0B661231D
      Actions:
        instanceActions:
          ActionId: aws:ec2:stop-instances
          Parameters:
            startInstancesAfterDuration: PT1M
          Targets:
            Instances: instanceTargets
    Metadata:
      aws:cdk:path: FisExampleStack/fis-template-demo-stop-instance
Parameters:
  SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  VPCParameterValue:
    Type: AWS::EC2::VPC::Id
