# Run the cleanup script in AWS account
name: AwsMatrix

# Controls when the workflow will run
on:
  # schedule:
  #   # Run weekly on Friday at ~8am MT - infrequent runs to allow merging PRs
  #   - cron: '0 14 * * FRI'

  # Use for initial testing
  push:
    inputs:
      region:
        required: true
        type: string
        default: eu-west-1

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        required: true
        type: string
        default: eu-west-1

  # Allows this workflow to be called
  workflow_call:
    inputs:
      region:
        required: true
        type: string
        default: eu-west-1
        
concurrency: FisWorkshopBuildDestroyMatrix

run-name: AwsMatrix in ${{ inputs.region }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  matrix-deploy:
    uses: ./.github/workflows/aws_deploy.yml
    with:
      region: eu-west-1

  matrix-cleanup:
    needs: matrix-deploy
    uses: ./.github/workflows/aws_cleanup.yml
    with:
      region: eu-west-1
