# Run the cleanup script in AWS account
name: AwsCleanup

# Controls when the workflow will run
on:
  # schedule:
  #   # Run weekly on Friday at ~8am MT - infrequent runs to allow merging PRs
  #   - cron: '0 14 * * FRI'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        required: true
        type: string
        default: eu-west-1

  # Allows this workflow to be called
  workflow_call:
    inputs:
      region:
        required: true
        type: string
        default: eu-west-1
        
concurrency: FisWorkshopBuildDestroy-${{ inputs.region }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
      
env:
  AWS_REGION: ${{ inputs.region }}
  AWS_ROLE: "arn:aws:iam::575981814685:role/GitHubAutomationFisWorkshop"

run-name: AwsCleanup in ${{ inputs.region }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: install pre-reqs
        run: |
          set -x
          # curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          # nvm install stable
          npm install -g typescript
          npm install -g aws-cdk
          npm install -g npm-check-updates
          #
          # nvm version
          node --version
          npm version
          npm view typescript version
          npm view aws-cdk version
          cdk --version
          npm view npm-check-updates version
          aws --version

      - name: Git clone action 
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: GitHubFisWorkshopCleanup
          aws-region: ${{ env.AWS_REGION }}
          
      - name: run cleanup
        run: |
          cd resources/templates/
          bash -x cleanup-parallel.sh
