# This is a basic workflow to help you get started with Actions

name: PdfRender

# Controls when the workflow will run
on:
  # schedule:
  #   # Run daily at ~8am MT
  #   - cron: '0 14 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run linck checker
  pdfrender:
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout remp
        uses: actions/checkout@v2

      - name: spider links 
        run: |
          wget --spider -r -nd -nv  https://chaos-engineering.workshop.aws/ -o /tmp/run1.log

      - name: convert to pdf
        run: |
          set -x
          ls -a
          cd .github/workflows/pdfbuilder
          pwd
          ls -a
          npm install
          node example.js

      # - name: wget and check
      #   run: |
      #     wget --spider -r -nd -nv  https://chaos-engineering.workshop.aws/ -o /tmp/run1.log
      #     echo "List of broken links:"
      #     if grep -B1 'broken link!' /tmp/run1.log; then
      #       echo "Found broken links, exit with error"
      #       exit 1
      #     else
      #       echo "Found no broken links"
      #       exit 0
      #     fi
          
