# This is a basic workflow to help you get started with Actions

name: PdfRender

# Controls when the workflow will run
on:
  # schedule:
  #   # Run daily at ~8am MT
  #   - cron: '0 14 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run linck checker
  pdfrender:
    runs-on: ubuntu-latest
    
    steps: 
      # This configures git including credentials and allows push
      - name: checkout repo
        uses: actions/checkout@v2

      - name: spider links 
        run: |
          wget --spider -r -nd -nv  https://chaos-engineering.workshop.aws/ -o /tmp/run1.log
          cat /tmp/run1.log | perl -ne 'if (/URL:([^\s]+\.html)/) { print "$1\n"; }' > /tmp/run1.urls

      - name: convert to pdf
        run: |
          set -x
          ls -a
          cd .github/workflows/pdfbuilder
          pwd
          ls -a
          npm install
          node example.js

      # - name: shim pdf building
      #   run: |
      #     set -x
      #     cd .github/workflows/pdfbuilder
      #     date > merged.pdf

      # This works in conjunction with actions/checkout@v2
      - name: commit back to repo
        run: |
          set -x
          DATE=$( date '+%Y-%m-%d %H:%M:%S' )
          git config --global user.name "pdfrenderer"
          git config --global user.email "rudpot@amazon.com"
          git remote -v
          git fetch origin          
          git branch -a | fgrep 'automation/pdfrender' && git checkout automation/pdfrender || git checkout -b automation/pdfrender
          cd .github/workflows/pdfbuilder
          pwd
          ls -a
          cp merged.pdf ../../../deck/
          git add ../../../deck/merged.pdf
          git commit -m "PDF renderer ${DATE}"
          git push --set-upstream origin automation/pdfrender
          echo ${{ github.token }} | gh auth login --with-token
          git status
          gh pr create --title "PR for autogen PDF" --body "Pull request for a PDF rendering of workshop created by automation workflow."

          
